project:
  type: website

execute: 
  echo: false



website:
  title: "Math in raw html table"
  page-footer: ""
format:
  html:
    theme: 
      light: litera
      dark: solar
    css: styles.css
    toc: true
    link-external-newwindow: true


